apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # annotations:
  #   deployment.kubernetes.io/revision: "1"
  # generation: 22
  labels:
    run: gputest
  name: gputest
  namespace: default
spec:
  # progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      run: gputest
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      # creationTimestamp: null
      labels:
        run: gputest
    spec:
      containers:
      - args:
        - "1200"
        image: chrstnhntschl/gpu_burn:latest
        imagePullPolicy: Always
        name: gputest
        resources: 
          limits: 
            nvidia.com/gpu: 1
            #alpha.kubernetes.io/nvidia-gpu: 1 # requesting 1 GPUs
        # terminationMessagePath: /dev/termination-log
        # terminationMessagePolicy: File
      # dnsPolicy: ClusterFirst
      restartPolicy: Always
      # schedulerName: default-scheduler
      # securityContext: {}
      # terminationGracePeriodSeconds: 30

